version: "3"

services:
  short-creator:
    build:
      context: .
      dockerfile: main.Dockerfile
    env_file:
      - .env
    environment:
      - DEV=false
      - DOCKER=true
    ports:
      - "3123:3123"
    volumes:
      - ./data:/app/data
    entrypoint: ["node", "dist/index.js"]
