version: "3"

services:
  short-creator:
    build:
      context: .
      dockerfile: main.Dockerfile
    env_file:
      - .env
    environment:
      - DEV=false
    ports:
      - "5000:5000"
    entrypoint: ["node", "dist/index.js"]
